### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by YTR76** [ZDisket/TensorVox#11] opened 2022-02-19 22:06 UTC
[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
that's it, there's nothing else
plz fix plz :(

**Comment by ZDisket** [comment] 2022-02-19 23:06
@YTR76 Which model are you trying to load? Most of the time that error means it is either invalid, nothing exists in its folder, or the JSON file has gone missing or can't be accessed

**Comment by ZDisket** [comment] 2022-03-18 00:54
Closing because no reply.

**Closed by ZDisket** 2022-03-18 00:54 UTC

**Comment by qwani** [comment] 2023-09-08 10:40
the problem is that structure of unzipped folder by windows os zip extracting  is as following 
models : spy : spy : content
the problem occurs when extracting model zip files as it replicate the same folder name inside the folder that will cause the error message as tensorvox cannot reach json file and is looking for it  
the solution is to copy all folder content and paste it the main model name like 
 models :  spy  : content
